# GitHub Pages Configuration - PUBG License Dashboard
# إعدادات GitHub Pages - داش بورد إدارة تراخيص PUBG

title: "نظام إدارة تراخيص PUBG"
description: "نظام إدارة آمن واحترافي لتراخيص مجتمع ألعاب PUBG مع حماية متقدمة"
url: "https://darkcyberx.github.io"
baseurl: "/pubg-license-dashboard"

# Security and performance
enforce_ssl: true
theme: minima

# Language and direction
lang: ar
direction: rtl

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gzip
  - jekyll-compress-html

# Build settings
markdown: kramdown
highlighter: rouge
incremental: true

# Markdown processor
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Performance optimization
sass:
  style: compressed
  
# Compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude sensitive files from build
exclude:
  - .env
  - .env.local
  - .env.production
  - security-logs/
  - audit-logs/
  - "*.backup"
  - "*.bak"
  - "*.ps1"
  - "*.bat"
  - "*.exe"
  - "*.dll"
  - "*.log"
  - Logs/
  - Registry_Backup/
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - SECURITY_DEPLOYMENT_GUIDE.md

# Default layout and front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      
  - scope:
      path: "assets"
    values:
      cache: true

# Social links
github_username: darkcyberx

# Collections (if needed for future expansions)
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Timezone
timezone: UTC

# Encoding
encoding: utf-8

# Liquid settings
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Development settings (ignored in production)
livereload: true
open_url: false